language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: bellingard-github
    token:
      secure: "Zjx8KlbYPJN/7Fb1M1kEervLUF9V7QaPvY/JVNxG6Xr2tkkrUax7TTg6v2v+GDn9GoAleoKTrWojN7uBk0Ps1XhhIH0X8QL22IYEeEnVHFTHAUzEJJHsmeyAHsdshQxNw2AZ2VpzqUBedv/+s4sOylbbUCcMBv3LO2bFcKtM2OElkNI8KalYdcw02jCdXOJXMAWlVJ9FoQOQ6RrCDNEH+EHZU461ze+vS8HATblABFPcPaqqCyGWoYZzcI9FsnnjFwxdp+Mb5awDbB+FW0W8rvJzgWRPQOKFVkVXVKP1wlRt9lShpbIETD8LhHdqo+JCPMdYhklb2rJPvYy4WblcrCulVmPt+IImzOnFQT/75uOJAeh0vd6OooNjjU0j6gr+eDXjomBa9TbihImlNiTjWqm58eS2O7S1lRO4D6fUw8AjT4yYAJAxNsWIDtrI7AGWBK3XhP4IvIk9vX0cbd74pSCGY3/AG0K5BYTeFuVrcT8dLL4ox9V+Q2oxRv1d4G3/96cpb8J3MWDe+R8U+1AKZ1oFvXJ8Y0S4wcYSP2/FadGMydVxVfoeG28jIE7V0CpjHBpH/LJhefgG9rbRc5m89LpQ4RJp+BXLNSPJ4nr5sTK4VtYkyqexVGNKslnh5kmccI7ceDcpUoEJ4/S5UKgQKVseBHFAiWXdiKaWHGvV64c="

jdk:
  - oraclejdk8

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
